//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace PowerliftingApi.Frontend.Infrastructure.Models
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public enum DivisionFilter
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Any")]
        Any = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Open")]
        Open = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"G")]
        G = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Cadet")]
        Cadet = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Elite")]
        Elite = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"SubJuniors")]
        SubJuniors = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"Juniors")]
        Juniors = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"Masters")]
        Masters = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"Seniors")]
        Seniors = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"Masters1")]
        Masters1 = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"Masters2")]
        Masters2 = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"Masters3")]
        Masters3 = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"Masters4")]
        Masters4 = 12,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public enum EquipmentFilter
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Raw")]
        Raw = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Wraps")]
        Wraps = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Single")]
        Single = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Multi")]
        Multi = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Straps")]
        Straps = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"Sleeves")]
        Sleeves = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"Bare")]
        Bare = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"Unlimited")]
        Unlimited = 7,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public enum FederationFilter
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Any")]
        Any = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Ffforce")]
        Ffforce = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Epf")]
        Epf = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Ipf")]
        Ipf = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Ffhmfac")]
        Ffhmfac = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Powerlifter
    {

        [System.Text.Json.Serialization.JsonPropertyName("best_bench")]
        public double? BestBench { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("best_deadlift")]
        public double? BestDeadlift { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("best_squat")]
        public double? BestSquat { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("bodyweight")]
        public double Bodyweight { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("division")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Division { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("equipment")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Equipment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("federation")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Federation { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rank")]
        public long Rank { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sex")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Sex { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("total")]
        public double? Total { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("weight_class")]
        public double? WeightClass { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PowerliftersQuery
    {

        [System.Text.Json.Serialization.JsonPropertyName("division_choice")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
public DivisionFilter DivisionChoice { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("equipment_choice")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
public EquipmentFilter EquipmentChoice { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("federation_choice")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
public FederationFilter FederationChoice { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("powerlifters")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Powerlifters { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sex_choice")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
public SexFilter SexChoice { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
    public enum SexFilter
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Any")]
        Any = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"M")]
        M = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"F")]
        F = 2,

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765