// <auto-generated>
//     This code was generated by Refitter version 2.2.0.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace PowerliftingApi.Frontend.Infrastructure.ApiContracts
{
    /// <summary>backend</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.2.0.0")]
    internal partial interface IBackend : IDisposable
    {
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>Powerlifters matching the supplied filters</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Invalid form data</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/powerlifters")]
        Task<ICollection<Powerlifter>> Powerlifters([Body] PowerliftersQuery body, CancellationToken cancellationToken = default);

    }


}