//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Division;
use super::sea_orm_active_enums::Equipment;
use super::sea_orm_active_enums::Sex;
use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "entries"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub division: Division,
    pub equipment: Equipment,
    pub sex: Sex,
    pub bodyweight: Decimal,
    pub weight_class: Decimal,
    pub squat1: Decimal,
    pub squat2: Decimal,
    pub squat3: Decimal,
    pub squat4: Decimal,
    pub bench1: Decimal,
    pub bench2: Decimal,
    pub bench3: Decimal,
    pub bench4: Decimal,
    pub deadlift1: Decimal,
    pub deadlift2: Decimal,
    pub deadlift3: Decimal,
    pub deadlift4: Decimal,
    pub best_squat: Decimal,
    pub best_bench: Decimal,
    pub best_deadlift: Decimal,
    pub total: Decimal,
    pub meet_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Division,
    Equipment,
    Sex,
    Bodyweight,
    WeightClass,
    Squat1,
    Squat2,
    Squat3,
    Squat4,
    Bench1,
    Bench2,
    Bench3,
    Bench4,
    Deadlift1,
    Deadlift2,
    Deadlift3,
    Deadlift4,
    BestSquat,
    BestBench,
    BestDeadlift,
    Total,
    MeetId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Meets,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::N(256u32)).def(),
            Self::Division => Division::db_type().get_column_type().to_owned().def(),
            Self::Equipment => Equipment::db_type().get_column_type().to_owned().def(),
            Self::Sex => Sex::db_type().get_column_type().to_owned().def(),
            Self::Bodyweight => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::WeightClass => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Squat1 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Squat2 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Squat3 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Squat4 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Bench1 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Bench2 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Bench3 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Bench4 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Deadlift1 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Deadlift2 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Deadlift3 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Deadlift4 => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::BestSquat => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::BestBench => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::BestDeadlift => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::Total => ColumnType::Decimal(Some((8u32, 4u32))).def(),
            Self::MeetId => ColumnType::Integer.def().unique(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Meets => Entity::belongs_to(super::meets::Entity)
                .from(Column::MeetId)
                .to(super::meets::Column::Id)
                .into(),
        }
    }
}

impl Related<super::meets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
