//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "country")]
pub enum Country {
    #[sea_orm(string_value = "france")]
    France,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "division")]
pub enum Division {
    #[sea_orm(string_value = "any")]
    Any,
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "g")]
    G,
    #[sea_orm(string_value = "cadet")]
    Cadet,
    #[sea_orm(string_value = "elite")]
    Elite,
    #[sea_orm(string_value = "subjuniors")]
    Subjuniors,
    #[sea_orm(string_value = "juniors")]
    Juniors,
    #[sea_orm(string_value = "seniors")]
    Seniors,
    #[sea_orm(string_value = "masters")]
    Masters,
    #[sea_orm(string_value = "masters1")]
    Masters1,
    #[sea_orm(string_value = "masters2")]
    Masters2,
    #[sea_orm(string_value = "masters3")]
    Masters3,
    #[sea_orm(string_value = "masters4")]
    Masters4,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "equipment")]
pub enum Equipment {
    #[sea_orm(string_value = "any")]
    Any,
    #[sea_orm(string_value = "raw")]
    Raw,
    #[sea_orm(string_value = "wraps")]
    Wraps,
    #[sea_orm(string_value = "single")]
    Single,
    #[sea_orm(string_value = "multi")]
    Multi,
    #[sea_orm(string_value = "straps")]
    Straps,
    #[sea_orm(string_value = "sleeves")]
    Sleeves,
    #[sea_orm(string_value = "bare")]
    Bare,
    #[sea_orm(string_value = "unlimited")]
    Unlimited,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "federation")]
pub enum Federation {
    #[sea_orm(string_value = "ffforce")]
    Ffforce,
    #[sea_orm(string_value = "epf")]
    Epf,
    #[sea_orm(string_value = "ipf")]
    Ipf,
    #[sea_orm(string_value = "ffhmfac")]
    Ffhmfac,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sex")]
pub enum Sex {
    #[sea_orm(string_value = "m")]
    M,
    #[sea_orm(string_value = "f")]
    F,
}
